version: "3"
services:
  server1-server:
    build:
      context: ./server1
      dockerfile: Dockerfile
    ports:
      - "8081:8081"
#    links:
#      - redis
#    depends_on:
#      - redis
    networks:
      - bubblebabble-network
    volumes:
      - bb-volume:/home/bb

#  redis:
#    image: "redis"
#    networks:
#      - 

  server2-server:
    build:
      context: ./server2
      dockerfile: Dockerfile
    ports:
      - "8082:8082"
    volumes:
      - bb-volume:/home/bb
    depends_on:
      - server1-server

  mongodb:
    image: mongo
    container_name: mongodb
    restart: always
    ports:
      - 27017:27017
    volumes:
      - ./mongodb:/data/db
    environment:
      - MONGO_INITDB_ROOT_USERNAME=soolo
      - MONGO_INITDB_ROOT_PASSWORD=soolo
      - MONGO_INITDB_DATABASE=chat

networks:
  bubblebabble-network:

volumes:
  bb-volume:
