spring:
  profiles:
    include: aws

  #    redis:
  #      host: localhost
  #      port: 6379

  #    jpa:
  #      properties:
  #        hibernate:
  #          show_sql: true
  #          format_sql: true
  #          hbm2ddl:
  #            auto: update
  #      open-in-view: false
  #    thymeleaf:
  #      cache: 'false'

server:
  port: 8082
  compression:
    enabled: true
    mime-types: application/json,application/xml,text/html
    min-response-size: 2048

logging:
  level:
    org.hibernate.type.descriptor.sql: DEBUG

#com:
#  amazons:
#    sdk:
#      disableEc2Metadata: true

