spring:
  data:
    mongodb:
      uri: mongodb+srv://soolo:soolo@cluster0.nnm1vfo.mongodb.net/chat?retryWrites=true&w=majority

  #    redis:
  #      host: localhost
  #      port: 6379

  #    jpa:
  #      properties:
  #        hibernate:
  #          show_sql: true
  #          format_sql: true
  #          hbm2ddl:
  #            auto: update
  #      open-in-view: false
  #    thymeleaf:
  #      cache: 'false'

server:
  port: 8082
  compression:
    enabled: true
    mime-types: application/json,application/xml,text/html
    min-response-size: 2048

logging:
  level:
    org.hibernate.type.descriptor.sql: DEBUG

#com:
#  amazons:
#    sdk:
#      disableEc2Metadata: true

cloud:
  aws:
    stack:
      auto: false
    region:
      static: ap-northeast-2
    credentials:
      access-key: AKIA3JJJHL4TRLZWHJVN
      secret-key: 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